import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Financial Dashboard",
  description: "Generated by Nnajiofor Uchenna Franklin",
  keywords: ["Financial", "Dashboard", "Nnajiofor Uchenna Franklin"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${lato.variable}
         bg-[#FFFFFF] lg:bg-[#f5f7fa] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
